---
name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: juancarlosjr97/github-actions-workflows-to-rule-them-all/.github/workflows/shared-rust-tests.yml@31f6c4d5ecec2fd98290563b653899538b1ecce8 # 0.7.15
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
