---
name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: juancarlosjr97/github-actions-workflows-to-rule-them-all/.github/workflows/shared-rust-tests.yml@2d9955af5439fcb9dd1ee4037945423c104196ed # 0.7.42
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
