---
name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: juancarlosjr97/github-actions-workflows-to-rule-them-all/.github/workflows/shared-rust-tests.yml@6366e7e5afd05970de742e05620149c8c4865286 # 0.7.22
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
